name = "ControlCenter"
uuid = "8dd07d2c-7ebb-4b16-8d8a-fee69c218bb8"
authors = ["Malte Krug <malte.krug@uni-ulm.de> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.11"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
